title: Asma Neji
description: Junior Cybersecurity Engineer | Telecom • Networks • Cybersecurity • AI
baseurl: ""
url: "https://asma812.github.io"

markdown: kramdown
highlighter: rouge

# Navigation (simple top bar like tags)
navigation:
  - text: About
    url: /about/
  - text: Blog
    url: /blog/
  - text: Telecom Lessons
    url: /telecom/
  - text: Contact
    url: /contact/

# Dark mode default
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
